FROM bde2020/spark-base:3.2.1-hadoop3.2
WORKDIR /app
USER root
RUN apk --no-cache add  musl-dev linux-headers g++ gcc python3-dev

COPY ./batch_layer/requirements.txt /app/

RUN pip3 install -v --no-cache-dir -r /app/requirements.txt

COPY ./batch_layer/* /app/

# CMD ["spark-submit", "--master", "local[*]", "spark_script.py"]
CMD ["tail", "-f", "/dev/null"]