FROM python:3.9-slim

WORKDIR /app
COPY ./ingestion_layer/* /app/
COPY ./data/* /app/data/
# RUN apt-get update && apt-get install -y gcc libpq-dev
RUN pip3 install -r /app/requirements.txt
CMD ["python3", "/app/api_producer.py"]
